version: "2"

linters:
  default: standard
  disable:
    - errcheck
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - inline
        - shadow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
