name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.26.x", "1.27.x"]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Test
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload code coverage to codecov
        if: matrix.go == '1.27.x'
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage.out
          fail_ci_if_error: true
